apiVersion: v1
kind: Service
metadata:
  name: stagedb-mysql-svc
  namespace: stage   
  labels:                
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql  
  type: LoadBalancer
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: stagedb-mysql-deploy
  namespace: stage
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: root-password
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: testusr2-db-pvc  
          mountPath: "/var/lib/mysql"
      volumes:
      - name: testusr2-db-pvc    
        persistentVolumeClaim:
          claimName: testusr2-db-pvc
