apiVersion: v1
kind: Service
metadata:
  name: testusr2-app-svc
  namespace: stage
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testusr2-app-deploy
  namespace: stage
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: ptmjyothish/finapp1:v1
        name: finapp1-image
        ports:
        - containerPort: 80
          name: testusr2-port
        volumeMounts:
        - name: testusr2-app-pvc
          mountPath: "/var/www/html"
      volumes:
      - name: testusr2-app-pvc
        persistentVolumeClaim:
          claimName: testusr2-app-pvc
