---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-mysql-svc
  namespace: stage
  labels:                                                                         
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
    tier: fontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-mysql-deploy
  namespace: stage
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: fontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: fontend
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: 10.111.29.83 
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-password
                  key: password
